{% set version = "0.24.1" %}

package:
  name: xcp
  version: {{ version }}

source:
  url: https://github.com/tarka/xcp/archive/v{{ version }}.tar.gz
  sha256: a49555f31d68955ebc948d5a6a3a4dc80774210f1200a1a50ecd58b7ae19758b

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - xcp --help

about:
  home: https://github.com/tarka/xcp
  dev_url: https://github.com/tarka/xcp
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: An extended cp

extra:
  recipe-maintainers:
    - apcamargo
